config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :exercises

      resources :workouts

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "exercises#index"
  resources :exercises
  resources :workouts
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  # Direct associations

  has_many   :exercises,
             dependent: :destroy

  # Indirect associations

  has_many   :users,
             through: :exercises,
             source: :user

  # Validations

  validates :name, uniqueness: true

  validates :name, presence: true

  # Scopes
  
  def to_s
    name
  end
end

app/controllers/api/v1/workouts_controller.rb
class Api::V1::WorkoutsController < Api::V1::GraphitiController
  def index
    workouts = WorkoutResource.all(params)
    respond_with(workouts)
  end

  def show
    workout = WorkoutResource.find(params)
    respond_with(workout)
  end

  def create
    workout = WorkoutResource.build(params)

    if workout.save
      render jsonapi: workout, status: :created
    else
      render jsonapi_errors: workout
    end
  end

  def update
    workout = WorkoutResource.find(params)

    if workout.update_attributes
      render jsonapi: workout
    else
      render jsonapi_errors: workout
    end
  end

  def destroy
    workout = WorkoutResource.find(params)

    if workout.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: workout
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[show edit update destroy]

  def index
    @q = Workout.ransack(params[:q])
    @workouts = @q.result(distinct: true).includes(:exercises,
                                                   :users).page(params[:page]).per(10)
  end

  def show
    @exercise = Exercise.new
  end

  def new
    @workout = Workout.new
  end

  def edit; end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to @workout, notice: "Workout was successfully created."
    else
      render :new
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: "Workout was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_url, notice: "Workout was successfully destroyed."
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name)
  end
end

app/views/workouts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Workout #<%= workout.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= workout.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back workout, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

    <!--
      <div class="col">
        <%# link_to edit_workout_url(workout), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <%# end %>
      </div>

      <div class="col">
        <%# link_to workout, method: :delete, data: { confirm: "Do you really want to delete this workout?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <%# end %>
      </div>
    -->
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(workout.updated_at) %> ago
  </div>
</div>

app/views/workouts/_form.html.erb
<% was_validated = workout.errors.any? %>

<%= form_with(model: workout, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = workout.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% workout.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/workouts/_list_item.html.erb
<%= link_to workout, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= workout %>
    <small class="text-muted">
      <%= time_ago_in_words(workout.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/workouts/_workout_exercises.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Exercises

    <a data-toggle="collapse" href="#workout_exercises_new_form">
      Add exercise
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @workout.exercises.where(user: current_user).each do |exercise| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to exercise, exercise %>

        <% if current_user == exercise.user %>
          <%= link_to exercise, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="workout_exercises_new_form">
        <%= render partial: "workouts/workout_exercises_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/workouts/_workout_exercises_new_form.html.erb
<%= form_with(model: @exercise, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.hidden_field :workout_id, value: @workout.id %>

  <div class="form-group">
    <%= f.label :completed_on %>

    <%= f.date_select :completed_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :weight %>

    <%= f.text_field :weight, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :reps %>

    <%= f.text_field :reps, class: "form-control" %>
  </div>

  <%= f.submit "Create exercise", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/workouts/_workout_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users
  </div>

  <ul class="list-group list-group-flush">
    <% @workout.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/workouts/_workouts_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "workouts_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/workouts" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#workouts_filters">
  Show filters
</a>

app/views/workouts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Workout #<%= @workout.id %>
      </h2>

      <div class="card-body">
        <%= render "form", workout: @workout %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Workouts

      <%= link_to new_workout_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "workouts/workouts_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Workouts

        <%= link_to new_workout_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @workouts, partial: "list_item", as: :workout %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @workouts, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Workout
      </h2>

      <div class="card-body">
        <%= render "form", workout: @workout %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @workout, partial: "card", as: :workout %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "workouts/workout_exercises" %>
  </div>
</div>

<!--
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%#= render partial: "workouts/workout_users" %>
  </div>
</div>
-->